name: stock-predictor
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - yfinance
      - keras
      - tensorflow